name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          activate-environment: "true"

      - run: uv sync

      - uses: liskin/gh-problem-matcher-wrap@v3.0.0
        with:
          action: add
          linters: mypy

      - name: mypy
        run: mypy --show-column-numbers app
      - run: ty check . --output-format=github

  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.x"

      - uses: trim21/actions/prek@master

  pyright:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v8.1.0

      - run: uv sync

      - uses: jakebailey/pyright-action@v3.0.2
        with:
          # renovate: datasource=github-releases depName=microsoft/pyright
          version: "1.1.409"
